### ISSUE TITLE
Component#sendAction is deprecated

### ISSUE THREAD

**Issue by xtagon** [mharris717/ember-drag-drop#155]
Hi,

I'm seeing deprecation warnings like these every time I drag and drop something in my Ember app. I only started seeing this after updating from Ember 2 to Ember 3.

Is there a way to fix these warnings? I am using closure actions.

```
deprecate.js:120 DEPRECATION: You called <plic-match-ui@component:draggable-object::ember1505>.sendAction("action") but Component#sendAction is deprecated. Please use closure actions instead. [deprecation id: ember-component.send-action] See https://emberjs.com/deprecations/v3.x#toc_ember-component-send-action for more details.
        at logDeprecationStackTrace (http://localhost:4200/assets/vendor.js:49870:23)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:49964:11)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:49897:11)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:49964:11)
        at invoke (http://localhost:4200/assets/vendor.js:49976:11)
        at deprecate (http://localhost:4200/assets/vendor.js:49935:30)
        at Class.sendAction (http://localhost:4200/assets/vendor.js:45268:46)
        at Class.getObject (http://localhost:4200/assets/plic-match-ui.js:5665:28)
        at Class.handlePayload (http://localhost:4200/assets/vendor.js:153712:41)
```

Thanks

**Comment by xtagon** [comment]
I've traced it to here:

https://github.com/mharris717/ember-drag-drop/blob/687f7debed01f4ab38ee893748c87dfc74b23779/app/models/coordinator.js#L15-L21

**Comment by dgavey** [comment]
Funny, I thought we had refactored all of these out.  I'll try and get it fixed soon.  Of course, PR's are always welcome.

**Comment by dgavey** [comment]
I don't think that model is even getting used anymore.  That's legacy code.

**Comment by xtagon** [comment]
Hmm that's funny. I'm using 0.6.3 in my package.json and yarn.lock:

```
ember-drag-drop@^0.6.3:
  version "0.6.3"
  resolved "https://registry.yarnpkg.com/ember-drag-drop/-/ember-drag-drop-0.6.3.tgz#65e2adfffd427875a0fb2e9f15f470dcad2e5d3d"
  integrity sha512-rVrJW66IjFdujdbxEm24lX8XbaqMdGyqIQsF5iEOUlxHttNA1Fyqr8tXb2dL5VSAl32jv9WhLuGBpsOPMlgvBQ==
  dependencies:
    ember-cli-babel "7.1.3"
    ember-jquery-legacy "^1.0.0"
```

which is the latest version on the releases page right now

**Comment by xtagon** [comment]
Always happy to help out with a PR but in this case I don't really understand how that code is used or how to safely remove it.

**Comment by dgavey** [comment]
No problem, yeah I need to look into this a bit more. I'm sure we don't need this model anymore, but I need to verify that.

**Comment by rwwagner90** [comment]
@dgavey do you guys still need help removing these? I'm getting the warnings in my code.

**Comment by bensane** [comment]
Any update on this depreciation refactor?

**Comment by rwwagner90** [comment]
@dgavey please let me know if you need help removing these.

**Comment by dgavey** [comment]
@rwwagner90 If you want to create a PR for this, I'd happily merge and release a new version.

**Comment by rwwagner90** [comment]
@dgavey not sure if this works or not, but should fix the deprecation https://github.com/mharris717/ember-drag-drop/pull/180

**Comment by xtagon** [comment]
Appears to be fixed in https://github.com/mharris717/ember-drag-drop/releases/tag/v0.9.0-beta.0 but it says once it's been declared stable there will be an 0.9 release, but that was in 2021. Is this project dead?

**Comment by RobbieTheWagner** [comment]
@dgavey @mharris717 would you be interested in transferring this to adopted-ember-addons or adding some of us as maintainers here?

**Comment by dgavey** [comment]
Yes, but I don't own the repo. So I can't transfer it to you.  I would suggest forking it instead and republishing, then I can shut this down and point to a different one. Maybe NPM can somehow also point to the new repo, not sure.

**Comment by RobbieTheWagner** [comment]
Do you have any contact with @mharris717? Would he be willing to transfer it?

**Comment by dgavey** [comment]
I don't have any contact with him or ability to contact him anymore.
