### ISSUE TITLE
DEPRECATION: A property was modified inside the didInsertElement hook. 

### ISSUE THREAD

**Issue by andrei-sheina** [mharris717/ember-drag-drop#70]
`DEPRECATION: A property of <frontend@view:-outlet::ember1142> was modified inside the didInsertElement hook. You should never change properties on components, services or models during didInsertElement because it causes significant performance degradation. [deprecation id: ember-views.dispatching-modify-property]
        at HANDLERS.(anonymous function) (http://localhost:4202/assets/vendor.js:22015:7)
        at raiseOnDeprecation (http://localhost:4202/assets/vendor.js:21923:12)
        at HANDLERS.(anonymous function) (http://localhost:4202/assets/vendor.js:22015:7)
        at invoke (http://localhost:4202/assets/vendor.js:22031:7)
        at deprecate (http://localhost:4202/assets/vendor.js:21984:32)
        at Object.deprecate (http://localhost:4202/assets/vendor.js:32023:37)
        at Class.exports.default._emberMetalMixin.Mixin.create._Mixin$create.scheduleRevalidate (http://localhost:4202/assets/vendor.js:59292:22)
        at http://localhost:4202/assets/vendor.js:29536:32
        at Object.notifySubscribers (http://localhost:4202/assets/vendor.js:37936:11)`

This deprecation warning is triggered when you using draghandler. Triggered here - https://github.com/mharris717/ember-drag-drop/blob/master/addon/components/draggable-object.js#L40

P.S. I'm using Ember 2.5

**Comment by KirillSuhodolov** [comment]
@mharris717 and @andrei-sheina it can be easily fixed by wrapping changes at didInsert hook in to ```
Ember.run.scheduleOnce('afterRender', this, function() {..your code here..});
```

**Comment by dgavey** [comment]
I'm thinking of dropping the didInsertElement and using init instead, I believe that should fix it as well. Sorry it's been taking me a while lately.  I'll address some of these issues shortly

**Comment by dgavey** [comment]
Should be fixed in the latest release 0.4.1
